package com.appcoins.eskills2048;

import android.content.Intent;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import org.jetbrains.annotations.NotNull;

import java.util.List;

public class LaunchActivity extends AppCompatActivity {

  private static final int RESULT_OK = 1;
  private static final int RC_ESKILLS = 10003;

  public static final String USER_ID = "USER_ID";
  public static final String ROOM_ID = "ROOM_ID";
  public static final String WALLET_ADDRESS = "WALLET_ADDRESS";
  public static final String SESSION = "SESSION";

  private final String userId = "string_user_id";

  @Override protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    String url = BuildConfig.BASE_HOST_PAYMENT + "/transaction/eskills?"
        + "value=1&currency=USD&product=antifreeze&product_label=Become a champion (1v1)"
        + "&user_id=" + userId + "&domain=" + getPackageName() + "&sandbox=LIVE";

    Log.d("LaunchActivity", url);

    Intent intent = buildTargetIntent(url);
    try {
      startActivityForResult(intent, RC_ESKILLS);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  /**
   * This method generates the intent with the provided One Step URL to target the
   * AppCoins Wallet.
   * @param url The url that generated by following the One Step payment rules
   *
   * @return The intent used to call the wallet
   */
  private Intent buildTargetIntent(String url) {
    Intent intent = new Intent(Intent.ACTION_VIEW);
    intent.setData(Uri.parse(url));

    // Check if there is an application that can process the AppCoins Billing
    // flow
    PackageManager packageManager = getApplicationContext().getPackageManager();
    List<ResolveInfo> appsList = packageManager
        .queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
    for (ResolveInfo app : appsList) {
      if (app.activityInfo.packageName.equals("cm.aptoide.pt")) {
        // If there's aptoide installed always choose Aptoide as default to open
        // url
        intent.setPackage(app.activityInfo.packageName);
        break;
      } else if (app.activityInfo.packageName.equals("com.appcoins.wallet")) {
        // If Aptoide is not installed and wallet is installed then choose Wallet
        // as default to open url
        intent.setPackage(app.activityInfo.packageName);
      }
    }
    return intent;
  }

  @Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    if (requestCode == RC_ESKILLS && resultCode == RESULT_OK) {
      startActivity(buildMainActivityIntent(data));
      finish();
    }
  }

  @NotNull private Intent buildMainActivityIntent(Intent data) {
    Intent intent = new Intent(this, MainActivity.class);

    intent.putExtra(ROOM_ID, data.getStringExtra(ROOM_ID));
    intent.putExtra(USER_ID, userId);
    intent.putExtra(WALLET_ADDRESS, data.getStringExtra(WALLET_ADDRESS));
    intent.putExtra(SESSION, data.getStringExtra(SESSION));

    return intent;
  }
}
